<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwRM8o1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwRM8o1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWwRM8o1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWwRM8o1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWwRM8o1\App_KernelDevDebugContainer([
    'container.build_hash' => 'WwRM8o1',
    'container.build_id' => 'be37123a',
    'container.build_time' => 1675615173,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwRM8o1');
